name: Run Tests, Lint, and Build

on:
  pull_request:
    branches: ['*']
  # temporary for testing while developing
  push:
    branches: ['*']

env:
  NODE_VERSION: '16.x' # The Node version to use.

jobs:
  test-components:
    name: 'Build, Check Linting, and Test'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test

  lint-project:
    name: 'Check Formatting'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
      - run: npm run format:check
